name: "Deployment Workflow"
on:
  workflow_call:
    inputs:
      deploy-environment:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
jobs:
  deploy-to-dev:
    name: "Deploy To DEV"
    runs-on: "ubuntu-latest"
    if: inputs.deploy-environment == 'dev'
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Artifact Detail
        run: ls -R
  deploy-to-qa:
    name: "Deploy To QA"
    runs-on: "ubuntu-latest"
    if: inputs.deploy-environment == 'qa'
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}

      - name: Artifact Detail
        run: ls -R

      - name: "Deploy"
        run: echo Deploying in ${{inputs.deploy-environment}}
