name: "Deployment Workflow"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
jobs:
  deploy-to-dev:
    name: "Deploy To Dev"
    runs-on: "ubuntu-latest"
    if: inputs.environment == 'dev'
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: Artifact Detail
        run: ls -R
