name: DotNetPocAzFunctions-Dev
on:
  pull_request:
    branches: [develop]
  push:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{github.event_name}}"
