name: develop-ci-cd
run-name: |
  ${{github.event_name == 'push' && format('Commit by {0} on {1}: {2}', github.actor, github.ref_name, github.event.head_commit.message)||
    github.event_name == 'pull_request' && format('PR by {0} on {1}: {2}',github.actor, github.ref_name, github.event.pull_request.title)}}

on:
  push:
    branches:
      - develop
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"

  pull_request:
    branches:
      - develop
    paths:
      - "src/**"
      - "tests/**"

env:
  BRANCH_NAME: "develop"
  DOTNET_VERSION: "9.0.x"
  PUBLISH_PROJECT_PATH: "${{github.workspace}}/src/DotNetPoC.Functions/"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH_NAME}}

      - name: Setup .NET SDK ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: publish
        if: ${{github.event_name == 'push'}}
        run: dotnet publish ${{env.PUBLISH_PROJECT_PATH}} --configuration Release --no-build --no-restore --output "${{github.workspace}}/publish-output"
      - name: "files"
        run: |
          ls -a
          echo ${{github.workspace}}

      - name: Upload published artifact
        if: ${{github.event_name == 'push'}}
        uses: actions/upload-artifact@v4.6.1
        with:
          path: "${{github.workspace}}/publish-output"
          name: develop-artifact
