name: pre-prod-ci-cd
run-name: Running pipeline on branch ${{github.ref}} on event ${{github.action}} by ${{github.actor}}
on:
  workflow_dispatch:
    inputs:
      deploy-on:
        description: "Select environment"
        required: true
        type: choice
        options:
          - test
          - dev

  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  BRANCH_NAME: "develop"
  DOTNET_VERSION: "9.0.x"
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verify running against ${{env.BRANCH_NAME}} branch
        run: |
          if [ "${{ github.ref }}" != "refs/heads/${{env.BRANCH_NAME}}" ]; then
            echo "Error: This workflow can only be run on the ${{env.BRANCH_NAME}} branch."
            exit 1
          fi
          echo "Running on the correct branch: ${{env.BRANCH_NAME}}"

      - name: Execution Environment Details
        run: echo "Environment - ${{github.event.inputs.environment}}, Triggered by event - ${{github.event_name}}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH_NAME}}

      - name: Setup .NET SDK ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
