name: pre-prod-ci-cd
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Select environment to build and deploy
        type: choice
        options:
          - dev
          - test

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Environment detail
        run: echo "Environment - ${{github.event.inputs.environment}}, Triggered by event - ${{github.event_name}}, Branch - ${{github.ref}}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
