name: dotnetpocazfunctions-develop-ci-cd
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{github.event_name}} on branch ${{github.ref}}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
