name: Deploy to QA
on:
  workflow_dispatch:

jobs:
  deploy-to-qa:
    name: Deploy To QA
    runs-on: "ubuntu-latest"
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: develop-artifact
          repository: ${{github.repository}}

      - name: Artifact Detail
        run: ls -R

      - name: "Deploy"
        run: echo Deploying in QA
