name: Deploy to QA
on:
  workflow_dispatch:
    inputs:
      run-id:
        required: true
        type: string
        description: Run Id of Development Build

jobs:
  deploy-to-qa:
    name: Deploy To QA
    runs-on: "ubuntu-latest"
    steps:
      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: develop-artifact
          repository: ${{github.repository}}
          run-id: ${{inputs.run-id}}
          github-token: ${{github.token}}

      - name: Artifact Detail
        run: ls -R

      - name: "Deploy"
        run: echo Deploying in QA
